version: '3.8'

services:
  web:
    build: ./PAS_app
    command: python manage.py run -h 0.0.0.0
    volumes:
      - ./PAS_app/:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=proxy_account_service_v1

volumes:
  postgres_data: