version: '3.8'

services:
    db:
        image: postgres:latest
        privileged: true
        ports: 
            - 5432:5432
        volumes:
        - postgres_data:/var/lib/postgresql/data/
        environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=proxy_account_service_v1
    pas_app:
        build: ./
        command: flask run --host=0.0.0.0
        volumes:
        - ./PAS_app:/usr/src/PAS_app/
        ports:
        - 5000:5000
        env_file:
        - ./env.dev
        depends_on:
        - db
  

volumes:
  postgres_data: