"""empty message

Revision ID: a4787bed5a46
Revises: 
Create Date: 2021-06-16 02:39:03.474148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4787bed5a46'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proxies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('ip_address', sa.String(length=15), nullable=False),
    sa.Column('port', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('ip_version', sa.String(length=5), nullable=False),
    sa.Column('renewed_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('valid_resources', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('resources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resources_abbreviation'), 'resources', ['abbreviation'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('login', sa.String(length=200), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('resource', sa.BigInteger(), nullable=False),
    sa.Column('api_key', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['resource'], ['resources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('locked_account', sa.BigInteger(), nullable=False),
    sa.Column('locked_proxy', sa.BigInteger(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['locked_account'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['locked_proxy'], ['proxies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locks')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_resources_abbreviation'), table_name='resources')
    op.drop_table('resources')
    op.drop_table('proxies')
    # ### end Alembic commands ###
